In [ ]:
import math
from Control import *
from Servo import *

In [ ]:
class Action:
    def __init__(self):
        self.servo=Servo()
        self.control=Control()
        self.servo.setServoAngle(15,90)
    def push_ups(self):
        xyz=[[0,50,0],[-100,23,0],[-100,23,0],[0,50,0]]
        for i in range(4):
            xyz[i][0]=(xyz[i][0]-self.control.point[i][0])/30
            xyz[i][1]=(xyz[i][1]-self.control.point[i][1])/30
            xyz[i][2]=(xyz[i][2]-self.control.point[i][2])/30
        for j in range(30):
            for i in range(4):
                self.control.point[i][0]+=xyz[i][0]
                self.control.point[i][1]+=xyz[i][1]
                self.control.point[i][2]+=xyz[i][2]
            self.control.run()
            time.sleep(0.01)
        for i in range(4):
            for i in range(50,120,1):
                self.control.point[0][1]=i
                self.control.point[3][1]=i
                self.control.run()
                time.sleep(0.01)
            for i in range(120,50,-1):
                self.control.point[0][1]=i
                self.control.point[3][1]=i
                self.control.run()
                time.sleep(0.01)
        xyz=[[55,78,0],[55,78,0],[55,78,0],[55,78,0]]
        for i in range(4):
            xyz[i][0]=(xyz[i][0]-self.control.point[i][0])/30
            xyz[i][1]=(xyz[i][1]-self.control.point[i][1])/30
            xyz[i][2]=(xyz[i][2]-self.control.point[i][2])/30
        for j in range(30):
            for i in range(4):
                self.control.point[i][0]+=xyz[i][0]
                self.control.point[i][1]+=xyz[i][1]
                self.control.point[i][2]+=xyz[i][2]
            self.control.run()
            time.sleep(0.01)
    def helloOne(self):  
        xyz=[[-20,120,-40],[50,105,0],[50,105,0],[0,120,0]]
        for i in range(4):
            xyz[i][0]=(xyz[i][0]-self.control.point[i][0])/30
            xyz[i][1]=(xyz[i][1]-self.control.point[i][1])/30
            xyz[i][2]=(xyz[i][2]-self.control.point[i][2])/30
        for j in range(30):
            for i in range(4):
                self.control.point[i][0]+=xyz[i][0]
                self.control.point[i][1]+=xyz[i][1]
                self.control.point[i][2]+=xyz[i][2]
            self.control.run()
            time.sleep(0.02)
        x3=(80-self.control.point[3][0])/30
        y3=(23-self.control.point[3][1])/30
        z3=(0-self.control.point[3][2])/30
        for j in range(30):
            self.control.point[3][0]+=x3
            self.control.point[3][1]+=y3
            self.control.point[3][2]+=z3
            self.control.run()
            time.sleep(0.01)
        for i in range(2):
            for i in range(92,120,1):
                self.servo.setServoAngle(11,i)
                time.sleep(0.01)
            for i in range(120,60,-1):
                self.servo.setServoAngle(11,i)
                time.sleep(0.01)
            for i in range(60,92,1):
                self.servo.setServoAngle(11,i)
                time.sleep(0.01)
        xyz=[[55,78,0],[55,78,0],[55,78,0],[55,78,0]]
        for i in range(4):
            xyz[i][0]=(xyz[i][0]-self.control.point[i][0])/30
            xyz[i][1]=(xyz[i][1]-self.control.point[i][1])/30
            xyz[i][2]=(xyz[i][2]-self.control.point[i][2])/30
        for j in range(30):
            for i in range(4):
                self.control.point[i][0]+=xyz[i][0]
                self.control.point[i][1]+=xyz[i][1]
                self.control.point[i][2]+=xyz[i][2]
            self.control.run()
            time.sleep(0.02)
        for i in range(90,130):
            self.servo.setServoAngle(15,i)
            time.sleep(0.02)
        for i in range(130,50,-1):
            self.servo.setServoAngle(15,i)
            time.sleep(0.02)
        for i in range(50,110):
            self.servo.setServoAngle(15,i)
            time.sleep(0.02)
    def helloTwo(self): 
        xyz=[[0,99,-30],[10,99,0],[10,99,0],[0,99,0]]
        for i in range(4):
            xyz[i][0]=(xyz[i][0]-self.control.point[i][0])/30
            xyz[i][1]=(xyz[i][1]-self.control.point[i][1])/30
            xyz[i][2]=(xyz[i][2]-self.control.point[i][2])/30
        for j in range(30):
            for i in range(4):
                self.control.point[i][0]+=xyz[i][0]
                self.control.point[i][1]+=xyz[i][1]
                self.control.point[i][2]+=xyz[i][2]
            self.control.run()
            time.sleep(0.02)    
        x3=(80-self.control.point[3][0])/30
        y3=(23-self.control.point[3][1])/30
        z3=(0-self.control.point[3][2])/30
        for j in range(30):
            self.control.point[3][0]+=x3
            self.control.point[3][1]+=y3
            self.control.point[3][2]+=z3
            self.control.run()
            time.sleep(0.01)
            
        for i in range(2):
            for i in range(92,120,1):
                self.servo.setServoAngle(11,i)
                time.sleep(0.01)
            for i in range(120,60,-1):
                self.servo.setServoAngle(11,i)
                time.sleep(0.01)
            for i in range(60,92,1):
                self.servo.setServoAngle(11,i)
                time.sleep(0.01)
        self.control.stop()
        for i in range(10):
            self.control.setpLeft()
    def hand(self):
        xyz=[[-20,120,-20],[50,105,0],[50,105,0],[-20,120,20]]
        for i in range(4):
            xyz[i][0]=(xyz[i][0]-self.control.point[i][0])/30
            xyz[i][1]=(xyz[i][1]-self.control.point[i][1])/30
            xyz[i][2]=(xyz[i][2]-self.control.point[i][2])/30
        for j in range(30):
            for i in range(4):
                self.control.point[i][0]+=xyz[i][0]
                self.control.point[i][1]+=xyz[i][1]
                self.control.point[i][2]+=xyz[i][2]
            self.control.run()
            time.sleep(0.02)
        
        for i in range(3):   
            x3=(100-self.control.point[3][0])/30
            y3=(40-self.control.point[3][1])/30
            z3=(10-self.control.point[3][2])/30
            for j in range(30):
                self.control.point[3][0]+=x3
                self.control.point[3][1]+=y3
                self.control.point[3][2]+=z3
                self.control.run()
                time.sleep(0.001)
                
        
            x3=(-20-self.control.point[3][0])/30
            y3=(120-self.control.point[3][1])/30
            z3=(20-self.control.point[3][2])/30
            for j in range(30):
                self.control.point[3][0]+=x3
                self.control.point[3][1]+=y3
                self.control.point[3][2]+=z3
                self.control.run()
                time.sleep(0.001)
            
            x0=(100-self.control.point[0][0])/30
            y0=(40-self.control.point[0][1])/30
            z0=(-10-self.control.point[0][2])/30
            for j in range(30):
                self.control.point[0][0]+=x0
                self.control.point[0][1]+=y0
                self.control.point[0][2]+=z0
                self.control.run()
                time.sleep(0.001)
            x0=(-20-self.control.point[0][0])/30
            y0=(120-self.control.point[0][1])/30
            z0=(-20-self.control.point[0][2])/30
            for j in range(30):
                self.control.point[0][0]+=x0
                self.control.point[0][1]+=y0
                self.control.point[0][2]+=z0
                self.control.run()
                time.sleep(0.001)
        xyz=[[55,78,0],[55,78,0],[55,78,0],[55,78,0]]
        for i in range(4):
            xyz[i][0]=(xyz[i][0]-self.control.point[i][0])/30
            xyz[i][1]=(xyz[i][1]-self.control.point[i][1])/30
            xyz[i][2]=(xyz[i][2]-self.control.point[i][2])/30
        for j in range(30):
            for i in range(4):
                self.control.point[i][0]+=xyz[i][0]
                self.control.point[i][1]+=xyz[i][1]
                self.control.point[i][2]+=xyz[i][2]
            self.control.run()
            time.sleep(0.02)
        
    def coquettish(self):
        xyz=[[80,80,0],[-30,120,0],[-30,120,0],[80,80,0]]
        for i in range(4):
            xyz[i][0]=(xyz[i][0]-self.control.point[i][0])/30
            xyz[i][1]=(xyz[i][1]-self.control.point[i][1])/30
            xyz[i][2]=(xyz[i][2]-self.control.point[i][2])/30
        for j in range(30):
            for i in range(4):
                self.control.point[i][0]+=xyz[i][0]
                self.control.point[i][1]+=xyz[i][1]
                self.control.point[i][2]+=xyz[i][2]
            self.control.run()
            time.sleep(0.02)
        while True:
            xyz=[[80,80,-30],[-30,120,30],[-30,120,30],[80,80,-30]]
            for i in range(4):
                xyz[i][0]=(xyz[i][0]-self.control.point[i][0])/30
                xyz[i][1]=(xyz[i][1]-self.control.point[i][1])/30
                xyz[i][2]=(xyz[i][2]-self.control.point[i][2])/30
            for j in range(30):
                for i in range(4):
                    self.control.point[i][0]+=xyz[i][0]
                    self.control.point[i][1]+=xyz[i][1]
                    self.control.point[i][2]+=xyz[i][2]
                self.control.run()
                time.sleep(0.02)
            
            xyz=[[80,80,30],[-30,120,-30],[-30,120,-30],[80,80,30]]
            for i in range(4):
                xyz[i][0]=(xyz[i][0]-self.control.point[i][0])/30
                xyz[i][1]=(xyz[i][1]-self.control.point[i][1])/30
                xyz[i][2]=(xyz[i][2]-self.control.point[i][2])/30
            for j in range(30):
                for i in range(4):
                    self.control.point[i][0]+=xyz[i][0]
                    self.control.point[i][1]+=xyz[i][1]
                    self.control.point[i][2]+=xyz[i][2]
                self.control.run()
                time.sleep(0.02)
                
    def swim(self):
        z=100*math.cos(45/180*math.pi)+23
        x=100*math.sin(45/180*math.pi)
        xyz=[[-x,0,z],[-78,0,100],[-78,0,-100],[-x,0,-z]]
        for i in range(4):
            xyz[i][0]=(xyz[i][0]-self.control.point[i][0])/30
            xyz[i][1]=(xyz[i][1]-self.control.point[i][1])/30
            xyz[i][2]=(xyz[i][2]-self.control.point[i][2])/30
        for j in range(30):
            for i in range(4):
                self.control.point[i][0]+=xyz[i][0]
                self.control.point[i][1]+=xyz[i][1]
                self.control.point[i][2]+=xyz[i][2]
            self.control.run()
            time.sleep(0.02)
        for i in range(3):
            for i in range(45,-45,-1):
                z=100*math.cos(i/180*math.pi)+23
                x=100*math.sin(i/180*math.pi)
                xyz=[[-x,0,z],[-78,0,100],[-78,0,-100],[-x,0,-z]]
                for i in range(4):
                    xyz[i][0]=(xyz[i][0]-self.control.point[i][0])
                    xyz[i][1]=(xyz[i][1]-self.control.point[i][1])
                    xyz[i][2]=(xyz[i][2]-self.control.point[i][2])
                for i in range(4):
                    self.control.point[i][0]+=xyz[i][0]
                    self.control.point[i][1]+=xyz[i][1]
                    self.control.point[i][2]+=xyz[i][2]
                self.control.run()
            for i in range(-45,45,1):
                z=100*math.cos(i/180*math.pi)+23
                x=100*math.sin(i/180*math.pi)
                xyz=[[-x,0,z],[-78,0,100],[-78,0,-100],[-x,0,-z]]
                for i in range(4):
                    xyz[i][0]=(xyz[i][0]-self.control.point[i][0])
                    xyz[i][1]=(xyz[i][1]-self.control.point[i][1])
                    xyz[i][2]=(xyz[i][2]-self.control.point[i][2])
                for i in range(4):
                    self.control.point[i][0]+=xyz[i][0]
                    self.control.point[i][1]+=xyz[i][1]
                    self.control.point[i][2]+=xyz[i][2]
                self.control.run()
        xyz=[[55,78,0],[55,78,0],[55,78,0],[55,78,0]]
        for i in range(4):
            xyz[i][0]=(xyz[i][0]-self.control.point[i][0])/30
            xyz[i][1]=(xyz[i][1]-self.control.point[i][1])/30
            xyz[i][2]=(xyz[i][2]-self.control.point[i][2])/30
        for j in range(30):
            for i in range(4):
                self.control.point[i][0]+=xyz[i][0]
                self.control.point[i][1]+=xyz[i][1]
                self.control.point[i][2]+=xyz[i][2]
            self.control.run()
            time.sleep(0.02)
        time.sleep(1)
        
    def yoga(self):
        xyz=[[55,78,0],[55,78,0],[55,78,0],[55,78,0]]
        for i in range(4):
            xyz[i][0]=(xyz[i][0]-self.control.point[i][0])/30
            xyz[i][1]=(xyz[i][1]-self.control.point[i][1])/30
            xyz[i][2]=(xyz[i][2]-self.control.point[i][2])/30
        for j in range(30):
            for i in range(4):
                self.control.point[i][0]+=xyz[i][0]
                self.control.point[i][1]+=xyz[i][1]
                self.control.point[i][2]+=xyz[i][2]
            self.control.run()
            time.sleep(0.02)
            
        y=100*math.cos(45/180*math.pi)+23
        x=100*math.sin(45/180*math.pi)
        xyz=[[-x,y,0],[0,0,123],[0,0,-123],[-x,y,0]]
        for i in range(4):
            xyz[i][0]=(xyz[i][0]-self.control.point[i][0])/30
            xyz[i][1]=(xyz[i][1]-self.control.point[i][1])/30
            xyz[i][2]=(xyz[i][2]-self.control.point[i][2])/30
        for j in range(30):
            for i in range(4):
                self.control.point[i][0]+=xyz[i][0]
                self.control.point[i][1]+=xyz[i][1]
                self.control.point[i][2]+=xyz[i][2]
            self.control.run() 
            time.sleep(0.02)
            
        for i in range(3):
            for i in range(45,-45,-1):
                y=100*math.cos(i/180*math.pi)+23
                x=100*math.sin(i/180*math.pi)
                xyz=[[-x,y,0],[0,0,123],[0,0,-123],[-x,y,0]]
                for i in range(4):
                    xyz[i][0]=(xyz[i][0]-self.control.point[i][0])
                    xyz[i][1]=(xyz[i][1]-self.control.point[i][1])
                    xyz[i][2]=(xyz[i][2]-self.control.point[i][2])
                for i in range(4):
                    self.control.point[i][0]+=xyz[i][0]
                    self.control.point[i][1]+=xyz[i][1]
                    self.control.point[i][2]+=xyz[i][2]
                self.control.run() 
            for i in range(-45,45,1):
                y=100*math.cos(i/180*math.pi)+23
                x=100*math.sin(i/180*math.pi)
                xyz=xyz=[[-x,y,0],[0,0,123],[0,0,-123],[-x,y,0]]
                for i in range(4):
                    xyz[i][0]=(xyz[i][0]-self.control.point[i][0])
                    xyz[i][1]=(xyz[i][1]-self.control.point[i][1])
                    xyz[i][2]=(xyz[i][2]-self.control.point[i][2])
                for i in range(4):
                    self.control.point[i][0]+=xyz[i][0]
                    self.control.point[i][1]+=xyz[i][1]
                    self.control.point[i][2]+=xyz[i][2]
                self.control.run() 
        xyz=[[55,78,0],[55,78,0],[55,78,0],[55,78,0]]
        for i in range(4):
            xyz[i][0]=(xyz[i][0]-self.control.point[i][0])/30
            xyz[i][1]=(xyz[i][1]-self.control.point[i][1])/30
            xyz[i][2]=(xyz[i][2]-self.control.point[i][2])/30
        for j in range(30):
            for i in range(4):
                self.control.point[i][0]+=xyz[i][0]
                self.control.point[i][1]+=xyz[i][1]
                self.control.point[i][2]+=xyz[i][2]
            self.control.run()
            time.sleep(0.02)
        time.sleep(1)


    def rest(self):
        z=100*math.cos(45/180*math.pi)+23
        x=100*math.sin(45/180*math.pi)
        xyz=[[-x,0,z],[-78,0,100],[-78,0,-100],[-x,0,-z]]
        for i in range(4):
            xyz[i][0]=(xyz[i][0]-self.control.point[i][0])/30
            xyz[i][1]=(xyz[i][1]-self.control.point[i][1])/30
            xyz[i][2]=(xyz[i][2]-self.control.point[i][2])/30
    
    def roll(self):
        z=100*math.cos(45/180*math.pi)+23
        x=100*math.sin(45/180*math.pi)
        xyz=[[-x,0,z],[-78,0,100],[-78,0,-100],[-x,0,-z]]
        for i in range(4):
            xyz[i][0]=(xyz[i][0]-self.control.point[i][0])/30
            xyz[i][1]=(xyz[i][1]-self.control.point[i][1])/30
            xyz[i][2]=(xyz[i][2]-self.control.point[i][2])/30
        for j in range(30):
            for i in range(4):
                self.control.point[i][0]+=xyz[i][0]
                self.control.point[i][1]+=xyz[i][1]
                self.control.point[i][2]+=xyz[i][2]
            self.control.run()
            time.sleep(0.02)
        for j in range(30):
            for i in range(4):
                self.control.point[i][0]+=xyz[i][0]
                self.control.point[i][1]+=xyz[i][1]
                self.control.point[i][2]+=xyz[i][2]
            self.control.run()
            time.sleep(0.02)

In [ ]:
if __name__=='__main__':
    action=Action()  
    time.sleep(2)
    control=Control()
    for x in range(2):
        #action.push_ups()
        #action.helloOne()
        #action.hand()
        #action.coquettish() 
        #action.swim() 
        #action.yoga() 
        #action.helloTwo()
        #action.rest()
        action.roll()
        time.sleep(3)
    control.relax(True)

In [ ]:
from IPython.display import display 
import ipywidgets as widgets 
from ipywidgets import interact, Layout 


In [ ]:
from ipywidgets import Text, IntSlider, Dropdown
# Erstelle ein neues Text-Eingabefeld tb1 und zeige es an.
tb1 = Text(value='Text eingeben', 
                   description='Text-Widget: ')
display(tb1)
# Erstelle IntSlider-Widget is1 und zeige es an.
is1 = IntSlider(value=7, min=0, max=10, 
                        step=1, description='IntSlider: ')
display(is1)
# Erstelle Dropdown-Widget dd1 und zeige es an
dd1 = Dropdown(options=['1', '2', '3'], 
                       value='2', description='Dropdown: ')
display(dd1) 

In [ ]:
print('Wert des Widgets is1 ist: ' + str(is1.value))  
print('Wert des Widgets dd1 ist: ' + str(dd1.value)) 

In [ ]:
import ipywidgets
from ipywidgets import Text, Button
# Erstelle zwei Text-Eingabefelder
textbox1 = Text(description='a'); display(textbox1)
textbox2 = Text(description='b');display(textbox2)
# ... einen Button
button = Button(description='Berechnen!', 
                        layout=Layout(width='200px'))
button.style.button_color = 'lightgreen'
display(button)
# ... und ein Text-Ausgabefeld für die Summe
textbox3 = Text(description='Summe')
display(textbox3)
# Definiere Eventhandler für den Button
def on_button_clicked(sender):
    a = int(textbox1.value)
    b = int(textbox2.value)
    textbox3.value = str(a+b)
# ... und weise ihn dem on_click-Ereignis zu
button.on_click(on_button_clicked)

In [ ]:
# myfunc1 gibt einen Text aus, der von x abhängt 
def myfunc1(x):  
    print('Auswahl: ' + str(x)) 
# interact erzeugt Dropdown-Widget 
interact(myfunc1, x = [1, 2, 3]); 

In [ ]:
# myfunc2 gibt den eingegebenen Text aus 
def myfunc2(x):  
    print('Ihre Eingabe: ' + str(x)) 
interact(myfunc2, x = 'Text eingeben'); 

In [ ]:
!pip3 install matplotlib
!pip install numpy --upgrade

In [ ]:
import matplotlib.pyplot as plt 
from numpy import arange,sin,pi 
# Definiere myplot-Funktion  
def myplot(xmax): 
 x = arange(0, xmax, 0.01);y = sin(2*pi*x); 
 plt.plot(x,y); 
# Erstelle ein Widget für den Plot mit Hilfe von interact 
interact(myplot, xmax = (pi/2,4*pi));

In [ ]:
from ipywidgets import FloatSlider, interactive_output, VBox
def myplot(xmax):
     x = arange(0, xmax, 0.01)
     y = sin(2*pi*x)
     plt.plot(x,y)
ui_xmax = FloatSlider(description='xmax', value=10, min=pi/2, max=2*pi);
out = interactive_output(myplot, {'xmax': ui_xmax}); 
display(VBox([ui_xmax,out], layout=Layout(width='50%',border='1px dotted blue')))

Neue Funktion, um Parameter für Roboter grafisch einzustellen.
Position Array 3x4?
Winkel Array 3x4
etc

In [ ]:
def func1(xmax,y): 
 x = arange(0, xmax, 0.01);y = sin(2*pi*x); 
interact(func1, xmax=(100),y=1); 

In [ ]:
import math
from Control import *
from Servo import *

from IPython.display import display 
import ipywidgets as widgets 
from ipywidgets import interact, Layout
from ipywidgets import Text, Button

In [ ]:
c = Control()
c.angle

def setPoints(xl,yl,zl,xr,yr,zr):
    links = ([xl,yl,zl])
    rechts = ([xr,yr,zr])
    c.point = [[xl,yl,zl],[xl,yl,zl],[xr,yr,zr],[xr,yr,zr]]
    c.run()
    
interact(setPoints, xl=(70,100),yl=(80,100),zl=(-16,16), xr=(70,100),yr=(80,100),zr=(-16,16));

button = Button(description='Relax', 
                        layout=Layout(width='200px'))
button.style.button_color = 'lightgreen'
display(button)
# Definiere Eventhandler für den Button
zaehler = 1
def on_button_clicked(sender):
    c.relax(True)
        
button.on_click(on_button_clicked)

In [ ]:
c.run()

In [ ]:
c.relax(True)

In [ ]:
c.relax(False)

In [ ]:
c.point

In [ ]:
c.checkPoint()

In [ ]:
!pip install ipywidgets

In [ ]:
from ipywidgets import Controller


In [ ]:
Controller()

### Battery Energy estimation
$$123 - {123\over(1 + (v/3.7)^{80})^{0.165}}$$

die Frage ist wie ist das bei 2 Zellen?

In [4]:
from ADS7830 import *
a = ADS7830 ()
a.power(0)

7.882352941176471

In [5]:
def remaining(voltage):
    v = voltage
    energy = (123 - 123/(1 + (v/(3.7*2))**80)**0.165)
    return energy

In [6]:
rest = remaining(a.power(0))
round(rest,2)

69.61

### LED Control

In [ ]:
from test import *
test_Led()

In [ ]:
from Led import *
led = Led()
led.colorWipe(led.strip, Color(10, 0, 0)) 
time.sleep(2)
led.colorWipe(led.strip, Color(0, 0, 0)) 
time.sleep(2)
led.rainbow(led.strip)

### Servo Control

In [44]:
from Servo import *
import numpy as np

servo=Servo()

fl = (4,3,2)
fr = (8,9,10)
rl = (7,6,5)
rr = (11,12,13)

joints = np.array([[4, 3, 2],[8, 9, 10],[7, 6, 5],[11, 12, 13]])
joints = joints.transpose()

fl = joints[:,0]
fr = joints[:,1]
rl = joints[:,2]
rr = joints[:,3]

rolls = joints[0,:]
hips = joints[1,:]
knees = joints[2,:]

In [60]:
def setAngles(q1=90.00):
        servo.setServoAngle(knees[0],180-q1)
        servo.setServoAngle(knees[1],q1)
        servo.setServoAngle(knees[2],180-q1)
        servo.setServoAngle(knees[3],q1)
        
from IPython.display import display 
import ipywidgets as widgets 
from ipywidgets import interact, Layout
from ipywidgets import Text, Button

from Control import *
c = Control()

interact(setAngles, q1=(18,162,0.1));

button = Button(description='Relax', 
                        layout=Layout(width='200px'))
button.style.button_color = 'lightgreen'
display(button)
# Definiere Eventhandler für den Button
zaehler = 1
def on_button_clicked(sender):
    c.relax(True)
        
button.on_click(on_button_clicked)

interactive(children=(FloatSlider(value=90.0, description='q1', max=162.0, min=18.0), Output()), _dom_classes=…

Button(description='Relax', layout=Layout(width='200px'), style=ButtonStyle(button_color='lightgreen'))

#### Trying to control all angles separately

In [29]:
angles = np.array(c.angle)
angles = angles.transpose()



        
from IPython.display import display 
import ipywidgets as widgets 
from ipywidgets import interact, Layout
from ipywidgets import Text, Button

from Control import *
c = Control()

angles = np.ones((3,4))*90

@interact(q1=90)
def setAngles(q1=90,q2=90,q3=90,q4=90,q5=90,q6=90,q7=90,q8=90,q9=90,q10=90,q11=90,q12=90):
    angles = np.array([[q1, q4, q7, q10], [q2, q5, q8, q11], [q3, q6, q9, q12]])
    for i, x in enumerate(angles[:,0]):
        servo.setServoAngle(joints[i,0],180-x)
    for i, x in enumerate(angles[:,1]):
        servo.setServoAngle(joints[i,1],x)
    for i, x in enumerate(angles[:,2]):
        servo.setServoAngle(joints[i,2],180-x)
    for i, x in enumerate(angles[:,3]):
        servo.setServoAngle(joints[i,3],x)
        
@interact(q=90)      
def setKnees(q,q1=90,q2=90,q3=90,q4=90,q5=90,q6=90,q7=90,q8=90,q9=90,q10=90,q11=90,q12=90):
    setAngles(q1,q2,q,q4,q5,q,q7,q8,q,q10,q11,q)
    
button = Button(description='Relax', 
                        layout=Layout(width='200px'))
button.style.button_color = 'lightgreen'
display(button)
# Definiere Eventhandler für den Button
zaehler = 1
def on_button_clicked(sender):
    c.relax(True)
        
button.on_click(on_button_clicked)

interactive(children=(IntSlider(value=90, description='q1', max=270, min=-90), IntSlider(value=90, description…

interactive(children=(IntSlider(value=90, description='q', max=270, min=-90), IntSlider(value=90, description=…

Button(description='Relax', layout=Layout(width='200px'), style=ButtonStyle(button_color='lightgreen'))

In [52]:
#vielleicht geht winkel setzen noch kompakter, muss noch für ungerade umstellen (180-q) :

angles = np.arange(12).reshape((3,4))
for ind, val in np.ndenumerate(angles):
    if (ind[1] /2) == True:
        servo.setServoAngle(joints[ind],180-val)
        print("uneven")
    else:
        servo.setServoAngle(joints[ind],val)
        print("even")
    print(ind,val)
print(angles)
print(joints)

even
(0, 0) 0
even
(0, 1) 1
uneven
(0, 2) 2
even
(0, 3) 3
even
(1, 0) 4
even
(1, 1) 5
uneven
(1, 2) 6
even
(1, 3) 7
even
(2, 0) 8
even
(2, 1) 9
uneven
(2, 2) 10
even
(2, 3) 11
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 4  8  7 11]
 [ 3  9  6 12]
 [ 2 10  5 13]]


#### Offset


1. getting calibration angles
estimated
q1 100
q2 55
q3 80
q4 100
q5 33
q6 68
q7 88
q8 45
q9 67
q10 93
q11 44
q12 73

In [77]:
c.calibration()
cangles = np.array(c.calibration_angle)
cangles = cangles.transpose()
cangles

array([[-10,   1,  11,   4],
       [-36, -47, -56, -45],
       [ 10,  23,  20,  16]])

In [80]:
angles = np.array(c.angle)
angles = angles.transpose()
angles

array([[90, 90, 90, 90],
       [ 0,  0,  0,  0],
       [90, 90, 90, 90]])

In [81]:
angles = angles + cangles
angles

array([[ 80,  91, 101,  94],
       [-36, -47, -56, -45],
       [100, 113, 110, 106]])

#### Testing with calibration
gehört noch ausgebessert. Zuordnung falsch?

In [7]:
import numpy as np
from Control import *
from Servo import *

servo=Servo()
c = Control()

cangles = np.array(c.calibration_angle)
cangles = cangles.transpose()

angles = np.array(c.angle)
angles = angles.transpose()
angles = angles + cangles

joints = np.array([[4, 3, 2],[8, 9, 10],[7, 6, 5],[11, 12, 13]])
joints = joints.transpose()

fl = joints[:,0]
fr = joints[:,1]
rl = joints[:,2]
rr = joints[:,3]

rolls = joints[0,:]
hips = joints[1,:]
knees = joints[2,:]

def setAngles(q1=90.00):
        for i,x in enumerate(angles[0,:]):
            if i == 1 or 3:
                servo.setServoAngle(joints[0,i],180-x)
            else:
                servo.setServoAngle(joints[0,i],x)
        for i, x in enumerate(angles[1,:]):
            servo.setServoAngle(joints[1,i],x)
        for i, x in enumerate(angles[1,:]):
            servo.setServoAngle(joints[2,i],x)
        servo.setServoAngle(knees[0],180-q1-cangles[2,1])
        servo.setServoAngle(knees[1],q1+cangles[2,0])
        servo.setServoAngle(knees[2],180-q1-cangles[2,2])
        servo.setServoAngle(knees[3],q1+cangles[2,3])
        
from IPython.display import display 
import ipywidgets as widgets 
from ipywidgets import interact, Layout
from ipywidgets import Text, Button

interact(setAngles, q1=(18,162,0.1));

button = Button(description='Relax', 
                        layout=Layout(width='200px'))
button.style.button_color = 'lightgreen'
display(button)
# Definiere Eventhandler für den Button
zaehler = 1
def on_button_clicked(sender):
    c.relax(True)
        
button.on_click(on_button_clicked)

interactive(children=(FloatSlider(value=90.0, description='q1', max=162.0, min=18.0), Output()), _dom_classes=…

Button(description='Relax', layout=Layout(width='200px'), style=ButtonStyle(button_color='lightgreen'))

In [8]:
for i, x in enumerate(angles[0,:]):
    print(i,x)
    #print(joints[0,i])
    #print(angles[i])
    #print(i.index)

for i, x in enumerate(angles[1,:]):
    print(i,x)
    #print(joints[0,i])
    #print(angles[i])
    #print(i.index)
    
for i, x in enumerate(angles[2,:]):
    print(i,x)
    #print(joints[0,i])
    #print(angles[i])
    #print(i.index)

0 88
1 88
2 92
3 92
0 90
1 90
2 64
3 64
0 140
1 140
2 90
3 90


In [101]:
angles

array([[ 76,  98, 106,  92],
       [ 44,  44,  24,  46],
       [108, 134,  92,  92]])